# Generated by Django 3.2.9 on 2021-12-08 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_las_name_userprofile_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersTests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('question_1', models.BooleanField(default=None)),
                ('question_2', models.BooleanField(default=None)),
                ('question_3', models.BooleanField(default=None)),
                ('question_4', models.BooleanField(default=None)),
                ('question_5', models.BooleanField(default=None)),
            ],
        ),
    ]
